name: pulse
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.1+2

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  change_app_package_name: ^1.5.0
  icons_launcher: ^3.0.1
  http: ^1.3.0
  intl: ^0.20.2
  flutter_bloc: ^9.1.0
  equatable: ^2.0.7
  url_launcher: ^6.3.1
  flutter_boring_avatars: ^2.0.1
  country_flags: ^3.2.0
  logger: ^2.5.0
  in_app_update: ^4.2.3
  icons_plus: ^5.0.0
  json_annotation: ^4.9.0
  timeago: ^3.2.2
  package_info_plus: ^8.3.0
  shared_preferences: ^2.5.3
  fade_shimmer: ^2.4.0
  fl_chart: ^0.71.0
  flutter_timezone: ^4.1.1
  flutter_dotenv: ^5.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  json_serializable: ^6.9.4
  build_runner: ^2.4.15

icons_launcher:
  image_path: "assets/images/logo.png"
  platforms:
    android:
      enable: true
    ios:
      enable: true

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/fonts/
    - .env

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat/Montserrat-Black.ttf
          weight: 900
        - asset: assets/fonts/Montserrat/Montserrat-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Montserrat/Montserrat-Bold.ttf
          weight: 700
        - asset: assets/fonts/Montserrat/Montserrat-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Montserrat/Montserrat-Medium.ttf
          weight: 500
        - asset: assets/fonts/Montserrat/Montserrat-Regular.ttf
          weight: 400
        - asset: assets/fonts/Montserrat/Montserrat-Light.ttf
          weight: 300
        - asset: assets/fonts/Montserrat/Montserrat-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Montserrat/Montserrat-Thin.ttf
          weight: 100
