name: Build & Release
on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: '21.x'
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.27.2'
      - run: flutter pub get
      - run: flutter build apk --release --split-per-abi
      - name: upload APK
        uses: ncipollo/release-action@v1
        with:
          artifacts: 'build/app/outputs/apk/release/*.apk'
          tag: v1.0.${{ github.run_number }}
          token: ${{ secrets.TOKEN }}
